/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ExercicioInterface;

/**
 *
 * @author Samuel
 */
public class Ex04Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Ex04
     */
    public Ex04Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldVisor = new javax.swing.JTextField();
        jButtonSete = new javax.swing.JButton();
        jButtonOito = new javax.swing.JButton();
        jButtonNove = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonQuatro = new javax.swing.JButton();
        jButtonCinco = new javax.swing.JButton();
        jButtonSeis = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonUm = new javax.swing.JButton();
        jButtonDois = new javax.swing.JButton();
        jButtonTres = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonPonto = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonAdicao = new javax.swing.JButton();
        jButtonCc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSete.setText("7");
        jButtonSete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSeteMouseClicked(evt);
            }
        });

        jButtonOito.setText("8");
        jButtonOito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOitoMouseClicked(evt);
            }
        });

        jButtonNove.setText("9");
        jButtonNove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNoveMouseClicked(evt);
            }
        });

        jButtonDivisao.setText("/");
        jButtonDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDivisaoMouseClicked(evt);
            }
        });

        jButtonQuatro.setText("4");
        jButtonQuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonQuatroMouseClicked(evt);
            }
        });

        jButtonCinco.setText("5");
        jButtonCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCincoMouseClicked(evt);
            }
        });

        jButtonSeis.setText("6");
        jButtonSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSeisMouseClicked(evt);
            }
        });

        jButtonMultiplicacao.setText("*");
        jButtonMultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMultiplicacaoMouseClicked(evt);
            }
        });

        jButtonUm.setText("1");
        jButtonUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUmMouseClicked(evt);
            }
        });

        jButtonDois.setText("2");
        jButtonDois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDoisMouseClicked(evt);
            }
        });

        jButtonTres.setText("3");
        jButtonTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTresMouseClicked(evt);
            }
        });

        jButtonSubtracao.setText("-");
        jButtonSubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubtracaoMouseClicked(evt);
            }
        });

        jButtonZero.setText("0");
        jButtonZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonZeroMouseClicked(evt);
            }
        });
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });

        jButtonPonto.setText(".");
        jButtonPonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPontoMouseClicked(evt);
            }
        });

        jButtonIgual.setText("=");
        jButtonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIgualMouseClicked(evt);
            }
        });
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButtonAdicao.setText("+");
        jButtonAdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdicaoMouseClicked(evt);
            }
        });

        jButtonCc.setText("CC");
        jButtonCc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonUm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDois, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOito, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButtonSete, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButtonNove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonZeroMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "0");
    }//GEN-LAST:event_jButtonZeroMouseClicked

    private void jButtonMultiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "*");
    }//GEN-LAST:event_jButtonMultiplicacaoMouseClicked

    private void jButtonSeteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSeteMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "7");
    }//GEN-LAST:event_jButtonSeteMouseClicked

    private void jButtonOitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOitoMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "8");
    }//GEN-LAST:event_jButtonOitoMouseClicked

    private void jButtonNoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNoveMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "9");

    }//GEN-LAST:event_jButtonNoveMouseClicked

    private void jButtonDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDivisaoMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "/");
    }//GEN-LAST:event_jButtonDivisaoMouseClicked

    private void jButtonQuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQuatroMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "4");
    }//GEN-LAST:event_jButtonQuatroMouseClicked

    private void jButtonCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCincoMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "5");
    }//GEN-LAST:event_jButtonCincoMouseClicked

    private void jButtonSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSeisMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "6");
    }//GEN-LAST:event_jButtonSeisMouseClicked

    private void jButtonUmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUmMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "1");
    }//GEN-LAST:event_jButtonUmMouseClicked

    private void jButtonDoisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDoisMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "2");
    }//GEN-LAST:event_jButtonDoisMouseClicked

    private void jButtonTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTresMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "3");
    }//GEN-LAST:event_jButtonTresMouseClicked

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonPontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPontoMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + ".");
    }//GEN-LAST:event_jButtonPontoMouseClicked

    private void jButtonIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIgualMouseClicked
        String valor = jTextFieldVisor.getText();
        System.out.println(">>>"+valor);
        Calculos calculos = new Calculos();
        String resultado = calculos.calculadora(valor);

        jTextFieldVisor.setText(resultado);
    }//GEN-LAST:event_jButtonIgualMouseClicked

    private void jButtonAdicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdicaoMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "+");
    }//GEN-LAST:event_jButtonAdicaoMouseClicked

    private void jButtonSubtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubtracaoMouseClicked
        String valor = jTextFieldVisor.getText();
        jTextFieldVisor.setText(valor + "-");
    }//GEN-LAST:event_jButtonSubtracaoMouseClicked

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonCcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCcActionPerformed

        jTextFieldVisor.setText("");
    }//GEN-LAST:event_jButtonCcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex04Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex04Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex04Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex04Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex04Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicao;
    private javax.swing.JButton jButtonCc;
    private javax.swing.JButton jButtonCinco;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonDois;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonNove;
    private javax.swing.JButton jButtonOito;
    private javax.swing.JButton jButtonPonto;
    private javax.swing.JButton jButtonQuatro;
    private javax.swing.JButton jButtonSeis;
    private javax.swing.JButton jButtonSete;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JButton jButtonTres;
    private javax.swing.JButton jButtonUm;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JTextField jTextFieldVisor;
    // End of variables declaration//GEN-END:variables
}
